Add Avatar and Executives page component
Code-the-Change-YYC/code-the-change-yyc-site pull request #27
Opened 2022-08-08 21:24 UTC by tylerlam1

Resolves #19.

**Web Page**
<img width="1653" alt="Screen Shot 2022-08-08 at 11 37 49 AM" src="https://user-images.githubusercontent.com/41935461/183517160-6675909a-6f24-4f00-b60d-c9f619da8f28.png">

**Mobile Page**
Top:
<img width="297" alt="Screen Shot 2022-08-08 at 2 21 21 PM" src="https://user-images.githubusercontent.com/41935461/183517208-80c113a1-cf5c-469c-b967-ab7fea9ac6fe.png">

Bottom:
<img width="343" alt="Screen Shot 2022-08-08 at 2 21 26 PM" src="https://user-images.githubusercontent.com/41935461/183517214-5760c731-aa75-4f06-8018-8dd92e255fc2.png">

Double checked to make sure links work as well.

2022-08-09 00:41 UTC, harsohailB requested changes

2022-08-09 00:41 UTC, harsohailB commented on pages/_app.js
>        {/* CONTAINER FOR CONTENT BELOW TO TEST NAVBAR IS IN RIGHT POSITION*/}
Can we also get rid of this?

2022-08-09 00:41 UTC, harsohailB commented on components/Executives.jsx
> +const Executives = () => {
Don't see this rendered anywhere

2022-08-09 06:16 UTC, tylerlam1 commented on components/Executives.jsx
> +const Executives = () => {
Will do

2022-08-09 06:20 UTC, tylerlam1 commented on components/Executives.jsx
> +const Executives = () => {
Done

2022-08-09 06:53 UTC, harsohailB approved these changes
Amazing! Good work! 🚢

2022-08-09 06:53 UTC, harsohailB commented on components/Avatar.jsx
> +    <Link href={`https://linkedin.com/in/${username}`}>
nit: open in new tab?

2022-08-10 03:52 UTC, topanb11 commented on components/Avatar.jsx
> +    <Link href={`https://linkedin.com/in/${username}`}>
agreeing with this

2022-08-10 03:57 UTC, topanb11 approved these changes
I can't see the execs in most recent preview but previous one looks fire

2022-08-10 06:03 UTC, tylerlam1 commented on components/Avatar.jsx
> +    <Link href={`https://linkedin.com/in/${username}`}>
Sounds g

2022-08-10 06:08 UTC, merged